# Generated by Django 3.2.5 on 2023-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_retated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='retated',
            field=models.ManyToManyField(related_name='related_users', to='accounts.MobileUser'),
        ),
    ]
