# Generated by Django 3.2.5 on 2023-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_retated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='retated',
            new_name='related',
        ),
    ]
