# Generated by Django 3.2.5 on 2023-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_retated_account_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
