# Generated by Django 3.2.5 on 2023-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230422_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
